module.exports = {
  apps: [
    {
      name: "sfs",
      script: "java",
      args: "-jar facturadorApp-2.1.jar server prod.yaml",
      cwd: "C:\\SFS_v-2.1",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "logs/sfs-error.log",
      out_file: "logs/sfs-out.log",
      merge_logs: true,
    },
    {
      name: "facturador",
      script: "main.py",
      interpreter: "python",
      cwd: "C:\\FacturadorDaemon",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      env: {
        PYTHONUNBUFFERED: "1",
        PYTHONIOENCODING: "utf-8",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "logs/error.log",
      out_file: "logs/out.log",
      merge_logs: true,
    },
  ],
};
